### ISSUE TITLE
Memory usage increases with every "check_all" call

### ISSUE THREAD

**Issue by utmandrew** [pyta-uoft/pyta#646]
Every "check_all" call increases the memory used by my Python process. I expect, under normal usage, that's not a big deal, but if you're running a long-running process that uses python_ta multiple times, it can lead to unbounded growth in the memory used by the process.

To replicate, create a file to check. Then call "python_ta.check_all(fname)" several times. Check the memory usage of your Python process before the first call and after every subsequent call.

**Comment by david-yz-liu** [comment]
Thanks for reporting this, @utmandrew. I fixed two memory issues for multiple `check_all` calls. Can you please try out the new release (https://pypi.org/project/python-ta/1.6.2b1/) and see if it runs okay for a few hours/days?

**Comment by utmandrew** [comment]
No dice. I still see an increase over time.  

Here are three files 
[testfiles.zip](https://github.com/pyta-uoft/pyta/files/5213566/testfiles.zip)

that I'm using to test. bad_runner.py has a single function in it. If you run this file in interactive mode, you can check memory usage. Then, call the function. Check memory usage. Call the function. Check memory usage, etc. You should see an increase with every invocation. It's similar to the call inside the web application I'm running.

**Comment by david-yz-liu** [comment]
@utmandrew a quick update: I am still looking into this, looks like there is something going on with pylint/astroid memory usage as well. Won't be a quick fix I'm afraid.

**Comment by utmandrew** [comment]
Thanks for the update. No worries -- we have a workaround: calling the pyta checks in a separate process.
